### ISSUE TITLE
[Feature request] Root partition specification/option

### ISSUE THREAD

**Issue by vanfanel** [randyrossi/bmc64#10]
Hi there!

As I commented on the lemon64 forum, it would be very good to have an option (on config.txt, cmdline.txt, whatever you think it's best!) to specify the root partition containing the system ROM files and media.
That way, it would be possible to multiboot this wonder along with other OSES on the same card :)

I am opening this to formally request the feature :)

**Comment by randyrossi** [comment]
Yes, please open an issue on the github site.  I am working on the fatfs
replacement now.  Thanks.

**Comment by randyrossi** [comment]
A sorry.  Saw this as email on my phone and didn't realize you did :)
