### ISSUE TITLE
Support for Pi4

### ISSUE THREAD

**Issue by asdfjkl** [randyrossi/bmc64#119]
The homepage mentions support for the Pi2 & Pi3. Any news/statements regarding support for the Pi4?

**Comment by randyrossi** [comment]
There are currently too many problems on the Pi4 for a release.
The Pi3 models are the best option for this project.

**Comment by lroby74** [comment]
Maybe a day exists a Rpi 4 release, using X64SC instead of X64 version?
There are some demos that works very bad with X64 only :(  
I guess if Rpi 4 may be helpfull for performance of X64SC

**Comment by rhester72** [comment]
Sadly, not even the Pi 4 is anywhere near powerful enough for cycle-exact at that level.  It takes a PC for that.

**Comment by lroby74** [comment]
Combain 64 on Raspberry PI 4 has X64SC.. still need trying it

Il giorno gio 30 lug 2020 alle ore 15:40 rhester72 <notifications@github.com>
ha scritto:

**Comment by rhester72** [comment]
You might want to try it.

Nothing will prevent the code from _running_, of course, but it has no hope whatsoever of running at full speed.

**Comment by lroby74** [comment]
tried X64SC on Combian64, can't keep 100% of speed and 50FPS neither, Sedai does it perfectly

**Comment by randyrossi** [comment]
Unfortunately, not going to happen on the Pi4.  Closing this.

**Comment by cleverca22** [comment]
what problems are preventing it from working on a pi4?
