### ISSUE TITLE
Plus4: order of cursor keys is wrong

### ISSUE THREAD

**Issue by SvOlli** [randyrossi/bmc64#125]
Using the GPIO keyboard adapter, in Plus4 mode the keys are in the following order:
down up left right
But they should be
left right up down

The attached patch fixes that. I hope the fix gets in the code before the release of 3.6-stable.

[plus4-gpio-keyboard.patch.txt](https://github.com/randyrossi/bmc64/files/4411777/plus4-gpio-keyboard.patch.txt)

**Comment by rhester72** [comment]
Wouldn't this affect all keyboard input, whether it's GPIO or USB?

The point: It may help GPIO users, but will it hurt other users?

**Comment by SvOlli** [comment]
I just double-checked: no.

The array is used at kernel.cpp line 739 only. And that code is obviously only for handling GPIOs.
