### ISSUE TITLE
Lose of audio / video synchronization in games (about 1 second delay) with ReSid

### ISSUE THREAD

**Issue by lroby74** [randyrossi/bmc64#13]
Trying a game from a TAP file "Attack of the mutant camels" (see link for download and test it), 
i've noticed a very noticeable delay between when I fire with spaceship (and you can see the shot on the screen) until when you hear the sound of the shot itself, (not less than 1 second).
 I'm using 1.0.7 for stability. Is it possible to significantly reduce this LAG? It's very annoying.

Link : http://www.edicola8bit.com/giochi.php?collana=special_program&console=c64
(you can download italian version or original one, is same game)

**Comment by lroby74** [comment]
Then.. if i try original "Attack of the mutant camels" game is perfect without LAG..   italian version "CAMMELLI" has LAG... so problem is on italian version. i close this ticket

**Comment by lroby74** [comment]
I've just noticed that italian PRG version works, is only when load from TAP file that there is LAG (loss of audio / video synchronization)

**Comment by lroby74** [comment]
I've noticed same issue on Galencia TAP version too on 1.0.9

**Comment by lroby74** [comment]
Lose of Audio / Video Sync happens with ReSid,

**Comment by lroby74** [comment]
ReSid issues about audio / video syncro  still presents

**Comment by randyrossi** [comment]
I'm going to put together a custom kernel image for you to get some insight into what's going on.  Probably in the next couple days.

**Comment by lroby74** [comment]
ok thank you!

Il giorno mer 3 apr 2019 alle ore 15:30 randyrossi <notifications@github.com>
ha scritto:

**Comment by randyrossi** [comment]
Here is an image you can try that will open a file and log some values for me to diagnose the issue.  Please run it until you hear the delay, then go to the menu and select 'Close Log' at the very bottom of the menu options.  It's important you close the log or else nothing will get written.   This will create a file called 'sound.log' in the root of the sdcard.  Please take the sound.log file and mail it to me.

The images are here:

https://accentual.com/bmc64/downloads/sound/kernel8-32.img
https://accentual.com/bmc64/downloads/sound/kernel7.img

Thanks!

**Comment by lroby74** [comment]
I am trying it now,
i need to play some games or stay on initial boot Basic screen of C64?
How many minutes are needed to hear the click?

Il giorno gio 4 apr 2019 alle ore 03:33 randyrossi <notifications@github.com>
ha scritto:

**Comment by lroby74** [comment]
ah ok sorry, delay during games not click.. now i understood

Il giorno gio 4 apr 2019 alle ore 03:33 randyrossi <notifications@github.com>
ha scritto:

**Comment by lroby74** [comment]
Here you are
sound.log attached

Thank you very much

Il giorno gio 4 apr 2019 alle ore 03:33 randyrossi <notifications@github.com>
ha scritto:

**Comment by randyrossi** [comment]
I don't see an attachment.  Maybe github filters them out.  Can you send me the log directly via email?

**Comment by randyrossi** [comment]
Ok, good news.  I found out what the issue was.  I needed to change the timing of the machine from 50.125 hz to 50 hz to match the actual vertical refresh rate of HDMI.  But I didn't realize that when you connect the Pi to a composite monitor, the vblank frequency actually is 50.125hz .  So the machine must have been producing a little bit of extra audio each frame and that was accumulating in the audio buffer over time.  That caused the delay.  I was able to play the same game (Attack of Mutant Camels) without any delay accumulating.

I will have a fix for this soon in the form of a menu option.  I don't think I can automatically detect whether the display is HDMI or composite so it will have to be the user that sets it.

**Comment by randyrossi** [comment]
FYI: I didn't see this before because I actually don't have a PAL composite monitor.  But I happen to have an HDMI upscaler that takes in PAL which helped me reproduce the issue.  I will put together a kernel so you can test on your end to see if it fixes your problem.

**Comment by lroby74** [comment]
Oh finally thank you!!!

However most of FB group members are using a composite CRT TV or monitor :D



Il giorno gio 4 apr 2019 alle ore 22:56 randyrossi <notifications@github.com>
ha scritto:

**Comment by lroby74** [comment]
It may be.. second Raspberry was connected to another CRT monitor via
Composite cable output too, i don't use HDMI monitors  (a part with mini
consoles like C64 mini, SNES mini, Playstation mini, etc.etc.)


Il giorno gio 4 apr 2019 alle ore 22:56 randyrossi <notifications@github.com>
ha scritto:

**Comment by randyrossi** [comment]
Okay, I think I have a fix you can try.

After installing this kernel, edit your cmdline.txt and change it to have machine_timing=pal-composite

https://accentual.com/bmc64/downloads/sound3/kernel8-32.img
https://accentual.com/bmc64/downloads/sound3/kernel7.img

If this works, I will push a release this weekend with the fix.  Let me know if you (or friends) see any more 'audio drift' with this new setting.

**Comment by lroby74** [comment]
Finally! It's perfect, thank you!!!

I love it.. I tried Attack of the mutant camels and then Galencia, both are
perfect!!!!

i am soo happy!

Il giorno ven 5 apr 2019 alle ore 05:49 randyrossi <notifications@github.com>
ha scritto:

**Comment by lroby74** [comment]
Problem solved with version 1.3 of BMC64 and setting "machine_timing=pal-composite" into file CMDLINE.TXT
