### ISSUE TITLE
Gamepad with buttons from 16 to 20, not listed in Configure USB Gamepad menù

### ISSUE THREAD

**Issue by tostati** [randyrossi/bmc64#130]
Hi. I have a joypad that use button from 15 to 20. Those are fundamental buttons: select, start, digital u-d-l-r.
But in Gamepad Configuration buttons list arrive to 15.
is possible to add more buttons in the list, to get 16-17-18-19-20 working?
This 'cause my joystick is a very good one, wireless, with long battery life and good plastik.

**Comment by moogthedog** [comment]
Seconded.  I have a wired 8bitdo controller where the hat appears as high-numbered buttons.

**Comment by rhester72** [comment]
@randyrossi this patch: https://github.com/randyrossi/bmc64/files/5914413/circle_patch_gamepad_buttons.zip

corrects the above described issue, first mentioned here:

https://github.com/randyrossi/bmc64/issues/158

Please note that it is a patch-to-a-patch that expands the scope of my initial (already-integrated) patch to all USB gamepads, mirroring the same fix applied by the Circle team (https://github.com/rsta2/circle/commit/e067d306725e5c967fb28be9611978bc229140af).
