### ISSUE TITLE
BMC64 For Raspberry 400

### ISSUE THREAD

**Issue by Festuceto** [randyrossi/bmc64#173]
Will you implement compatibility with Raspberry 4 or 400? @randyrossi

**Comment by WebbedQuasar** [comment]
https://github.com/randyrossi/bmc64/issues/150

**Comment by randyrossi** [comment]
No I decided not to.  The Pi 4 is quite slow to boot and there were changes to the video pipeline that would require a lot of work to get going.  This project is best suited for the Pi3.
