### ISSUE TITLE
[FR] Datasette counter missing for loading many games TAP files

### ISSUE THREAD

**Issue by lroby74** [randyrossi/bmc64#18]
Would be possible to add Datasette counter please?

some of us have some TAPs files with each several games inside..

But in this moment is not possible to load games from second to last one..

**Comment by lroby74** [comment]
Another problem of Datasette counter missing is that some games like for example Turrican 2 ask to rewind tape to a certain point of tape to continue and it's not possible ATM

**Comment by foxp4v** [comment]
It would be nice, if this feature will be implemented, to have a status bar with the counter that is contextually displayed when a .tap is attacched.

**Comment by lroby74** [comment]
Status bar and counter present and working!!
