### ISSUE TITLE
Pro Micro instead of Keyrah

### ISSUE THREAD

**Issue by omiq** [randyrossi/bmc64#182]
I made a pro micro usb HID device, so I can use the real C64 keyboard AND do "user port" projects. Unfortunately while it is recognized fine by my Mac, the BMC64 Pi does not recognize it.

I found on the inter webs someone says use "usbhid.quirks=0x2341:0x8037:0x040" in cmdline.txt but that seems to be for Raspbian - anything I can do on BMC64 or is it basically impossible?

**Comment by mcgurk** [comment]
You don't have to do that yourself. There is readymade very versatile keyboard controller firmware for ProMicro called Soarers keyboard controller:
https://github.com/mcgurk/Arduino-USB-HID-RetroJoystickAdapter/tree/master/C64_keyboard

If you wan do everything yourself, you cannot use Arduino IDE with default libraries. With Arduine IDE ProMicro is multiple USB-devices same time and it is primarily USB-serial-device. It makes it incompatible with many devices.

**Comment by omiq** [comment]
The Arduino and C64 parts are working - I have the Arduino working with the keyboard and it is great when plugged in to my Mac using Vice - but the Pi doesn't recognize it for use with BMC64.

So from what I can tell you are saying the problem with getting it to work with BMC64 us I used the Arduino IDE?

**Comment by mcgurk** [comment]
Right, you cannot use Arduino IDE to make it USB-keyboard. I know that it seems to work with Mac ja Windows and many other devices, but it doesn't work with many simple devices which doesn't understand combination of many USB-devices. When simple device asks "what kind of USB-device you are", ProMicro made with Arduino IDE answers "I'm USB-serial device".

**Comment by omiq** [comment]
Ah ok that makes sense, thank you!

**Comment by mcgurk** [comment]
Soarers firmware in my link is not made with Arduino IDE. 
Other ways to create code for ProMicro is Atmel tools like Atmel Studio IDE.

Here is my example for Atmel Studio IDE to create pure USB-joystick device:
https://github.com/mcgurk/Arduino-USB-HID-RetroJoystickAdapter/tree/master/C64_joystick_atmelstudio

**Comment by omiq** [comment]
Yeah I saw just now he uses avrdude, so I am grabbing that from Homebrew but I will also check out using Atmel studio too so I can make custom solution - thank you! :)

**Comment by omiq** [comment]
Works perfectly, thank you @mcgurk !!
