### ISSUE TITLE
[FR] disable Pi power LED

### ISSUE THREAD

**Issue by ted210** [randyrossi/bmc64#194]
It would be great if the power LED could be disabled.  I have my Pi mounted inside my C64 breadbin and I can see the red LED glow through the keys which is about the only thing reminding me that I'm not using a real C64!

**Comment by rhester72** [comment]
Nothing to do with BMC64 (as what you're asking for is a function of the Raspberry PI/firmware)...however, the below does wonders on everything except the 3A+ (whose power light will stubbornly stay on no matter WHAT you do).  And there's always black electrical tape...

Add as desired to config.txt:

    # Disable Ethernet LEDs

    dtparam=eth_led0=14
    dtparam=eth_led1=14

    # Disable the PWR LED
    dtparam=pwr_led_trigger=none
    dtparam=pwr_led_activelow=off

    # Disable the Activity LED
    dtparam=act_led_trigger=none
    dtparam=act_led_activelow=off

**Comment by ted210** [comment]
Thank you. I have a 3A+ (Faszination C64) so will tape/blu tack it.  I may try to desolder it and remove it completely as long as that doesn't break anything else on the Pi.
