### ISSUE TITLE
Sometimes joystick-input freezes

### ISSUE THREAD

**Issue by mcgurk** [randyrossi/bmc64#2]
Thanks for great software! This is first time when I see software emulator to sync for display so that everything goes to frame. I have pursued that for years and with countless emulators and platforms. I use this for testing https://csdb.dk/release/?id=8904.

I have one strange problem though. Defender of the Crown freezes after some time. Sometimes it freezes in first seconds at map screen and one time I got to play couple of minutes and it froze to swordplay (there I clearly saw that joystick locked to up-position). Most of the time I can do couple of moves in the map until it freezes. Sometimes cursor disappears (joystick locks to some direction) and sometimes cursor stays at it place (joystick freezes to free position). Freeze is not actually right word, because emulation doesn't freeze. Animations goes on and music plays, but joystick doesn't respond. Same thing happens with USB-gamepad and GPIO-joystick. I tested with Raspberry Pi 2 and Raspberry Pi 3 B+. Here is the game I use for testing:
https://csdb.dk/group/?id=146

**Comment by randyrossi** [comment]
Was this seen with version 1.0.4?  I will try the game you mentioned and see if I have the same issue.

**Comment by mcgurk** [comment]
Yes, I have this problem with 1.0.4 too.

**Comment by lroby74** [comment]
I am having same problem with 1.0.7.. sometimes for  at once, one of directions of joysticks stops works. then restart normally..

**Comment by lroby74** [comment]
With last versions (1.0.8 & 1.0.9) i've not had this issue anymore

**Comment by mcgurk** [comment]
Just played Defender of the Crown through successfully with 1.0.9. This was first time lockup didn't occured. I close the issue.
