### ISSUE TITLE
Darker image using HDMI TVs / monitors

### ISSUE THREAD

**Issue by lroby74** [randyrossi/bmc64#20]
Hello,
many friends that are using BMC64 with an HDMI TV / monitors complain that image is darker of normal while  using same Raspberry and same BMC64 on a CRT TV / monitor via composite cable , image is brighter.
Is possible to modify some settings for raise brightness on HDMI output?

**Comment by randyrossi** [comment]
Things like brightness or contrast sounds like the job of the TV.  The Pi just outputs pixels and it's up to the display to control things like that.  Have they tried adjusting the TV settings?

**Comment by lroby74** [comment]
Many of them find the image dark even with the screen controls at maximum, and in all cases the image is always darker than other solutions (Retropie, Combian for example)

**Comment by randyrossi** [comment]
I would first experiment with different video modes described in the docs for config.txt.  I've noticed a big difference between the default NTSC 60hz mode and the default PAL 50hz mode.  The 50hz mode doesn't look as vibrant as the 60hz.  It's possible Combian's video mode is different which accounts for the different experience.  But you can try various 50hz modes and see what works best:

There are a bunch to chose from here:  

https://www.raspberrypi.org/documentation/configuration/config-txt/video.md

**Comment by lroby74** [comment]
Fixed with screen controls of 1.6 version
