### ISSUE TITLE
Emulator crashes when turning off scanlines in 1080p@50hz

### ISSUE THREAD

**Issue by ghost** [randyrossi/bmc64#209]
Hi Randy,

I've found that version 3.9 consistently crashes when scanlines are turned off within the crt shader menu when running at 1080p@50hz.

The only change I have made from the stock setup other than adding the c64 roms is to add the resolution information taken from the raspberry pi online config.txt guide entered for 1080p@50hz into the machine.txt file as below, which I believe are correct. All other settings within the machines.txt file remain unaltered. A photo of the crash screen is also attached.

[C64/PAL/HDMI/VICE 1080p@50Hz]
disable_overscan=1
sdtv_mode=18
hdmi_group=1
hdmi_mode=31
machine_timing=pal-hdmi
scaling_params=384,240,1152,720

![bmc64_scanline_crash](https://user-images.githubusercontent.com/98667554/151677749-236ba68f-79fb-4422-bec0-5407b8909e3d.jpg)

**Comment by randyrossi** [comment]
I can't repro on my Pi2.  Please let me know what Pi model you are running.

**Comment by randyrossi** [comment]
Problem was on user's Pi3.  Changing gpu_mem=64 to gpu_mem=128 resolved this.  But it's not clear why.  Same config worked for me with gpu_mem=64.
