### ISSUE TITLE
Error mounting files with very long names

### ISSUE THREAD

**Issue by foxp4v** [randyrossi/bmc64#21]
Hello, thank you for your great work, i've found an issue mounting files (i've tried .tap and .crt images, both gave the same error) with very long filenames, example: Fiendish Freddy's Big Top o' Fun + International Soccer + Flimbo's Quest + Klax (Europe) (C 64 Games System).crt 
This returns "failed to attach cart image". It would be nice to have this fixed so romsets like TOSEC could be used without renaming tons of files. Thanks.

**Comment by randyrossi** [comment]
Thanks for reporting.  I have a fix for this which will come out soon.
