### ISSUE TITLE
successful build using Arm GNU Toolchain (12.3.rel1) report

### ISSUE THREAD

**Issue by theflyingape** [randyrossi/bmc64#250]
On my **Fedora 39** workstation, I'd like to report that I can build off your latest git pull for my **Pi 3B+** running off a Commodore 1902 composite monitor by using the latest [Arm GNU Toolchain](https://developer.arm.com/Tools%20and%20Software/GNU%20Toolchain) with the environment setup:
```
# Arm Developer: https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads
export ARM_VERSION=12.3.rel1
export ARM_HOME="$HOME/BIG/arm-gnu-toolchain-${ARM_VERSION}-x86_64-arm-none-eabi"
export PATH="$PATH:${ARM_HOME}/bin"
```
... and also the packages `sudo install automake bison compat-flex flex libfl-static xa`

That said, the VICE 3.3  `configure` generated does not work with the newer toolchain, so I ran `autoupdate` and `autoreconf -i -f` as a first defense. Next, I hacked by commenting out the lines for `AC_CHECK_PROGS` for `byacc, yacc or bison` because these tests were failing despite being detected earlier as installed.  :+1: 

The resulting `configure` was closer, but had some mangled lines needing manual hygiene. I am attaching the result of thse edits as `configure.txt` here for any compare/diff for possible use as a `patch`:
[configure.txt](https://github.com/randyrossi/bmc64/files/13199740/configure.txt)

After copying the resulting kernel files over to the SD card, it booted into VIC 20 composite and showed me "4.1" in the menu's About.
```
$  ll kernel*.img*
-rwxr-xr-x 1 rhurst rhurst 2437456 Oct 29 20:25 kernel8-32.img
-rwxr-xr-x 1 rhurst rhurst 3061936 Oct 29 20:25 kernel8-32.img.c64
-rwxr-xr-x 1 rhurst rhurst 2437456 Oct 29 20:25 kernel8-32.img.pet
-rwxr-xr-x 1 rhurst rhurst 2393092 Oct 29 20:25 kernel8-32.img.plus4
-rwxr-xr-x 1 rhurst rhurst 1302672 Oct 29 20:25 kernel8-32.img.plus4emu
-rwxr-xr-x 1 rhurst rhurst 2447736 Oct 29 20:25 kernel8-32.img.vic20
```
There was also this elf file built, but I **did not copy** that over the `start.elf` that came with the **3.9** image:
```
$ ll *.elf
-rwxr-xr-x 1 rhurst rhurst 5486628 Oct 29 20:25 kernel8-32.elf
```
![image](https://github.com/randyrossi/bmc64/assets/19166945/4eb44023-1d3f-4976-adaf-dcbc0247bd42)

**Comment by rhester72** [comment]
I suspect you will find the resulting build for the Pi Zero hangs with a black screen - all later toolchains have has this effect for reasons I never really bothered to examine.  Builds for all other models (except 4, of course) work as expected.

**Comment by theflyingape** [comment]
Sure, all of the 3.x releases are for "Not Recommended for New Design" Pi boards. Being new to this "bare metal" scene, I won't invest much for my tinkering trying to use an old toolchain.

I am curious about the 4.x code tree on where it might be headed and figured I give this a workout, if only to use as a reference.  I am infatuated with the 8BitDo [Retro Mechanical Keyboard](https://www.amazon.com/dp/B0CCP8KYGG), which does not work with bmc64 v3.9, and would like to inspect further as to why/how and if ... 

If anything, I can always re-make this into a VIC 20 kiosk running **Mega-Cart**! :100:
