### ISSUE TITLE
[FR] Mouse 1351 Support

### ISSUE THREAD

**Issue by corasaniti** [randyrossi/bmc64#26]
Woudl be nice to be able to use the USB mouse that emulates a 1351 mouse for use with Geos
Thanks

**Comment by lroby74** [comment]
It works in 1.8 version, if i saw correctly, maybe this FR would be to close?

**Comment by corasaniti** [comment]
works correctly in 1.8 version. Thanks to Randy :-)

It is great to be able use Geos with a USB mouse. works also with a wireless mouse :-)
Thanks
