### ISSUE TITLE
Yellow flash on screen top right

### ISSUE THREAD

**Issue by x48x4b** [randyrossi/bmc64#273]
Hello,

I have bmc64-3.9 installed on a RPi 3B+. 
So far runs okay. 
But since I have made a snapshot, I get a yellow flash graphic on screen top right. 
The "flash" is  updated approx twice a seconds. 
What does that mean? 
How can I get rid of that? 
Where is the description of this?

Regards

**Comment by Kugelblitz360** [comment]
You need a better power supply. The flash is the standard cry for help of the Raspberries that they do not get enough power and need to throttle down.

**Comment by x48x4b** [comment]
Thanks a lot. Great to know. Yes, before the "flash" appeared, I actually exchanged the power supply, because the new one looked nicer :-) . Although it had the same amp rating. I will have to switch back to the ugly one :-( .
