### ISSUE TITLE
Speedlink Competition Pro Extra USB joystick?

### ISSUE THREAD

**Issue by x48x4b** [randyrossi/bmc64#277]
Hi,

I have a new Speedlink Competition Pro Extra USB joystick.
The joystick perfectly works in my Vice/C64/Linux setup.

The joystick is not recognized in my BMC64/C64/Raspberry Pi 3B+ setup.
(though an old Logitech USB joystick was recognized).

Anything I could do about it?

Best regards

**Comment by Kugelblitz360** [comment]
It should work. ANY joystick needs to be plugged in when BMC boots (power on). Anything you plug in later is not recognized. Maybe that is your problem?

**Comment by x48x4b** [comment]
Hi,
Thanks for your rapid answer. 
I did read the manual and plugged in the joystick before the boot, but without success.
(I have an older Logitech Wingman USB joystick that is working in this configuration.
Unfortunately the Wingman is not really suited for my games.)
Best regards

**Comment by mcgurk** [comment]
Just shot in the dark: 

After Googling about that Joystick, it seems that it is more complicated than just normal USB-joystick:
https://steamcommunity.com/discussions/forum/1/3185654583879949408

It might be "multi-USB-device", which are not supported by Circles, which are handling USB-devices in BMC64.
https://github.com/randyrossi/bmc64/issues/235

Another possibility is that it changes its mode somehow to something incompatible mode.

What ever reason is, right place to create issue is to Circle github:
https://github.com/rsta2/circle
As long as it doesn't work with Circle, it cannot work with BMC64. If it works with current Circle version, then fix might be to get updated Circle version to BMC64.

I would say that easiest fix is to get basic Competition Pro or similar USB-joystick without any complicated features.

**Comment by x48x4b** [comment]
Thanks.

I have created the issue here:

https://github.com/rsta2/circle/issues/476

**Comment by x48x4b** [comment]
... and BTW: I wish there was a list of compatible USB joysticks.

**Comment by Kugelblitz360** [comment]
Well there are at least three revisions of this joystick (mine works, the revision before that works but has serious lag issues) making it really difficult to maintain a usable list and if Speedlink really changed behaviour so that it changed its ID while plugged in, just return it.

**Comment by Kugelblitz360** [comment]
https://hardwaretester.com/gamepad is a great tool to see what is happening with your stick.

**Comment by x48x4b** [comment]
"https://hardwaretester.com/gamepad": Just works perfect with this great tool. Everything as one would expect.
Alas not in BMC64.

SPEEDLINK COMPETITION PRO Game Controller for Android (Vendor: 0079 Product: 181c)

That is the unit that is currently widely sold here. And mechanically it is very fine.

On a local second hand sale there is a "Competition PRO SL-6602 Speedlink". Is that any good in BMC64?

**Comment by x48x4b** [comment]
Maybe, I have to add that the  Speedlink Competition Pro Extra USB joystick is recognized on my 12 year old Raspberry Pi B as follows:

pi@raspberrypi:~ $ date ; uname -a
Sat Sep 21 21:52:01 CEST 2024
Linux raspberrypi 5.10.103+ #1529 Tue Mar 8 12:19:18 GMT 2022 armv6l GNU/Linux
pi@raspberrypi:~ $ jstest /dev/input/js0
Driver version is 2.1.0.
Joystick (SPEEDLINK COMPETITION PRO Game Controller for Android ) has 8 axes (X, Y, Z, Rz, Gas, Brake, Hat0X, Hat0Y)
and 15 buttons (BtnA, BtnB, BtnC, BtnX, BtnY, BtnZ, BtnTL, BtnTR, BtnTL2, BtnTR2, BtnSelect, BtnStart, BtnMode, BtnThumbL, BtnThumbR).
Testing ... (interrupt to exit)
Axes:  0:     0  1:     0  2:     0  3:     0  4:     0  5:     0  6:     0  7:     0 Buttons:  0:off  1:off  2:off  3:off  4:off  5:off  6:off  7:off  8:off  9Axes:  0:     0  1:     0  2:     0  3:     0  4:     0  5:     0  6:     0  7:     0 Buttons:  0:off  1:off

**Comment by x48x4b** [comment]
As suggested by "mcgurk", I have raised an issue in https://github.com/rsta2/circle/issues/476

Now we have the result.

We did tests and the result is, that the joystick does indeed work in circle. 
However it does not have a standard mapping (see https://github.com/rsta2/circle/issues/476).

Today, the  "Speedlink Competition Pro Extra USB" is very widely  offered joystick and it is notably  working flawlessly in my Vice on Linux/Intel. Therefore, we can safely assume that Vice has found a way to deal with this non-standard mapping.

My conclusion is, that there should be a way that BMC64 would handle gamepads without standard mapping.
Maybe you can just take a look at the relevant Vice code.

BTW: mcgurk advice "... I would say that easiest fix is to get basic Competition Pro or similar USB-joystick without any complicated 'Extra'-features. ...", in my opinion is not really a helpful advice as long as there is no whitelist of compatible joysticks for BMC64.

**Comment by Kugelblitz360** [comment]
But you can configure Gamepads in BMC64. If the joystick does not change IDs, simply configure it?

bmc64/README.md at master · randyrossi/bmc64 · GitHub<https://github.com/randyrossi/bmc64/blob/master/README.md#gamepad-config>
________________________________
Von: x48x4b ***@***.***>
Gesendet: Sonntag, 22. September 2024 22:51
An: randyrossi/bmc64 ***@***.***>
Cc: Boris Schneider-Johne ***@***.***>; Comment ***@***.***>
Betreff: Re: [randyrossi/bmc64] Speedlink Competition Pro Extra USB joystick? (Issue #277)


As suggested by "mcgurk", I have raised an issue in rsta2/circle#476<https://github.com/rsta2/circle/issues/476>

Now we have the result.

We did tests and the result is, that the joystick does indeed work in circle.
However it does not have a standard mapping (see rsta2/circle#476<https://github.com/rsta2/circle/issues/476>).

Today, the "Speedlink Competition Pro Extra USB" is very widely offered joystick and it is notably working flawlessly in my Vice on Linux/Intel. Therefore, we can safely assume that Vice has found a way to deal with this non-standard mapping.

My conclusion is, that there should be a way that BMC64 would handle gamepads without standard mapping.
Maybe you can just take a look at the relevant Vice code.

BTW: mcgurk advice "... I would say that easiest fix is to get basic Competition Pro or similar USB-joystick without any complicated 'Extra'-features. ...", in my opinion is not really a helpful advice as long as there is no whitelist of compatible joysticks for BMC64.

**Comment by x48x4b** [comment]
In the BMC64 configuration menu (activated by the key F12) under USB Gamepads, no joystick is reported to be detected. Thus there is no way to configure anything in the menu.
(Despite the fact that "circle" detects the joystick).

**Comment by x48x4b** [comment]
I suspect that in "kernel.cpp", line 711/712 no gamepad is reported, for whatever reason.

CUSBGamePadDevice *game_pad =
        (CUSBGamePadDevice *)mDeviceNameService.GetDevice(DeviceName, FALSE);

**Comment by x48x4b** [comment]
We did some other tests in "circle". See latest posts in https://github.com/rsta2/circle/issues/476

Conclusion: BMC64 uses an obsolete "circle" version.

Is there a way to build an updated BMC64 version correcting this?

**Comment by x48x4b** [comment]
@BMC64 developpers:
Could you kindly inform me if you plan to prepare a new BMC64 release using the current Circle version 47?
(the current official BMC64 release according to the file timestamps is from January 2, 2022 and has Circle version 40).

Please ses latest posts in https://github.com/rsta2/circle/issues/476

Thanks in advance!

HK

**Comment by x48x4b** [comment]
See https://github.com/rsta2/circle/issues/476

![IMG_20241020_202450](https://github.com/user-attachments/assets/5eaacb52-abc5-4938-8006-705c1ce1e8b9)
