### ISSUE TITLE
Use of a C64 motherboard

### ISSUE THREAD

**Issue by dr-prodigy** [randyrossi/bmc64#286]
Hi @randyrossi,
this is not really an issue, but instead a request for information / support.

First of all, massive congrats on your project! Even though I own a real C64 already, it made me want to build a C64 replica out of spare pieces I have.
In particular, I'd like to box it inside a stock C64c case, along with a stock keyboard and with the support for the 2 joystick ports.
Being also in possession of an empty long board (250466, although I believe the exact version is not very important: they are all equivalent in this respect), my idea is to use it too, for a "mobo hack", in order to provide all the external connections (joysticks, power supply, possibly even audio and composite video) through it, and also to route the internal connections from and to the RPi, by soldering wires on the CIA areas etc..: while also simplifying the whole assembly, this would make it appear the most possibly faithful from the outside.

Now, digging this opportunity, I made a scheme to check all the required connections, but unfortunately I found out that they are substantially different in the respect of which joystick pins are wired in parallel to which keyboard pins:

![Screenshot from 2024-10-31 17-08-07](https://github.com/user-attachments/assets/e8ff285e-111f-42a8-bf06-78d8c60aa916)
so I surely cannot implement this "out of the box".

The hardware solution would then be to decouple them (by cutting tracks etc.) and to re-arrange them as per your connection scheme.

On the other hand, another solution instead would be modifying the software..
Question is now: is there a clear reason why the original "relationships" between keyboard and joystick ports were not preserved, and instead remapped to the current BMC64 scheme? Could it be possible, in your opinion, to modify the BMC64 code to work with all (or almost all) the stock connections (I think I could also try to do it myself, if you feel like it's feasible)?

I hope I made myself clear, thank you a lot in advance, and KUTGW! :+1: :+1:

**Comment by randyrossi** [comment]
There is an upverter project that interfaces both the keyboard and joystick
with a real keyboard.  So I think the original connections are preserved.
Maybe take a look at that project and see if what you are trying to do is
feasible?

https://upverter.com/design/rrossi/bmc64/


Randy Rossi

- "There are only two things that are hard about computer science; Naming
things, Cache Invalidation, and Off-by-one errors."

**Comment by dr-prodigy** [comment]
Hey there @randyrossi just for your understanding, this is what I meant :-) 
![img1](https://github.com/user-attachments/assets/9672af86-190d-4cdd-a929-60b19d50ef08)
![img2](https://github.com/user-attachments/assets/e75007ea-206c-4140-8e41-fb995d75da4b)
![img3](https://github.com/user-attachments/assets/d0daad66-96a5-4b94-aeb2-41f2be313536)

While I could workaround the keyboard by replicating the connector under my main PCB (the one in the middle, which is also a hat for the Pi), in order to use the joystick ports (which I connect via the CIA 1 socket) I had to cut the 2 direct GND connections located under the DIN ports (also had to desolder them both to be able to reach them).
![joy connector](https://github.com/user-attachments/assets/b85a7e5a-6c5c-4dfa-8c02-fc66833f57d7)

Anyway, job done 👍
