### ISSUE TITLE
[FR] Status bar turning on / off from menú

### ISSUE THREAD

**Issue by lroby74** [randyrossi/bmc64#29]
Would be nice to have a way for turning on / off status bar from menú.

I see it when i change drive's type but then will hide after 1/2 seconds.
It seems that drives lights are not working yet 
same thing for "T:" (i don't understand if is for TAP name file or for counter),
is always empty

**Comment by randyrossi** [comment]
There is a prefs menu option : show never, always or on activity.  Is that not working?
Lights are working for me.  No red or green blocks for you?
T" is for tape and should show the counter.  Was working for me when I tested but maybe a last minute change broke it?

**Comment by randyrossi** [comment]
FYI: Drive lights don't work for IEC file system devices.  Only real drives.

**Comment by lroby74** [comment]
I didn't knew that!!!

YES! Status bar working!

Tape counter working with Datasette status

Drives LED working!!

WOW!

Il giorno ven 12 apr 2019 alle ore 13:29 randyrossi <
notifications@github.com> ha scritto:
