### ISSUE TITLE
1581 Drive emulation sound missing

### ISSUE THREAD

**Issue by lroby74** [randyrossi/bmc64#34]
I've noticed that using 1581 drive, emulated sound of loading is absent, where is present instead on others drive

**Comment by randyrossi** [comment]
I don't think there is sound emulation for the 1581.  I don't get sound on the desktop version either.

**Comment by lroby74** [comment]
i've tried on Vice 3.3 on PC, it's missing there too, i didn't thought to try that before opening issue, sorry
