### ISSUE TITLE
[FR] prefered CRT image file saved like default cart inserted

### ISSUE THREAD

**Issue by lroby74** [randyrossi/bmc64#35]
Would be nice to have an option for make a CRT file (like for example FASTLOAD cart) saved like default inserted. so when i turn on BMC64 from power off, i can have this CRT already present and active.

**Comment by jimizanei** [comment]
absolute a must ! 
jiffydos is nice, speed uo disk loading, but break tape routines, ...
crt like action replay 6 or epyx fast...speed up MORE disk loads, and you have more easy commands key and options ....  so you not need jiffydos kernal and , you can use also your tapes.
Ofcourse, with VICE you can do that.  with BMC64 will be nice IF you can select and save on prefs, one crt, and autostart when you switch on you BMC64,  before always load this crt manualy, every time you close BMC64.

**Comment by lroby74** [comment]
did with 1.6 and working! Thank you!

**Comment by jimizanei** [comment]
Thanks to YOU, Randy !! fine addons and fantastic the boot time...incredible!!!
now I wait only my lovely v20.......=)


  ----- Original Message -----
