### ISSUE TITLE
[FR] Autostart image (especially for PRGs) like in PC's Vice

### ISSUE THREAD

**Issue by lroby74** [randyrossi/bmc64#36]
Would be nicer and comfortable to have menu's choice "Autostart image" for easily and fastly load .PRG programs like in PC Vice 3.3
(probably would be doable it without even having to activate the IEC DRIVE 8 item??)

I see that using FileBrowser for loading some PRGs doesn't work (on BMC64 nor PC's Vice neither)

**Comment by randyrossi** [comment]
Added autostart to menu for prg, disks, carts, tapes,
