### ISSUE TITLE
Some .tap tapes won't load or even get to the Found .... text

### ISSUE THREAD

**Issue by TomDDG** [randyrossi/bmc64#4]
Tried a few .tap tapes and some work fine but others don't get past the first stage, basically you don't even get to the Found ... text. Robocop is one that doesn't work, Rambo First Blood Part 2 works fine.

**Comment by randyrossi** [comment]
These same .tap files work on desktop (windows/linux) Vice okay?  Are they available somewhere to download?

**Comment by TomDDG** [comment]
Sorry should have checked. The images are in the TOSEC collection so I just assumed they would be ok as they didn't have the [b] flag. VICE on Windows cannot load them either. I've found other versions which work so it must be something wrong with the images in the TOSEC collection. I'll close this.
