### ISSUE TITLE
[FR] Dual SID support 

### ISSUE THREAD

**Issue by lroby74** [randyrossi/bmc64#41]
Would be nice to have Dual SID support for some games like Super Mario Bros 64 and others:)

**Comment by randyrossi** [comment]
You can probably try this now by adding these to your vice.ini file.

SidStereoAddressStart=54304
SidStereo=1

That should create two sids.  You may have to change the start address of the 2nd sid to match what the program expects.

My guess is this will be too much for the Pi but it's worth trying.  I will give it a shot too.

**Comment by randyrossi** [comment]
Also, you might get the sound to work but it will still be mono.  I suspect both channels will get mixed into one.

**Comment by lroby74** [comment]
With these parameters in Vice.ini it works! Thank you!
