### ISSUE TITLE
Any hope for a RPI1 or RPI0 version?

### ISSUE THREAD

**Issue by cercamon** [randyrossi/bmc64#42]
This could have been discussed before, but I'd like a RPI1 or RPI0 version of BMC64 to see the light one day. Is this so difficult or not enough CPU power or RAM space to port it to the first or basic PI boards? Many thanks to whoever will take some time to try the porting.

Cercamon

**Comment by r10513** [comment]
Considering that rrossi is developing a pcb to use natively c64 keyboard and joystick, we can imagine how many people would be happy to refit their raspberry pi b in original c64 cases and make a "new" c64 without using retropie or combian with keyrah. 
Also, raspberry pi b has composite rca video out (not a combo jack, like rpi 2 or 3), that is much closer to the original TV out of c64.

**Comment by r10513** [comment]
Current 2.1 version with the kernel rrossi posted on lemon64 forum works on the original rasoberry pi model b (I tested with a USB keyboard and hdmi out).

**Comment by cercamon** [comment]
This is great news, thanks. Could you please post the URL pointing to the thread on Lemon64 forum?

**Comment by r10513** [comment]
Here it is https://www.lemon64.com/forum/viewtopic.php?t=70498&start=555

In data 25 luglio 2019 22:26:30 Cercamon <notifications@github.com> ha scritto:

**Comment by cercamon** [comment]
Many thanks. So very gentle of you to reply so fast. I found it in the meanwhile. Amazing. I'll give it a try tomorrow, with my RPI Model B.

**Comment by randyrossi** [comment]
This is available now under 'bmc64-lite'.  https://accentual.com/bmc64-lite
