### ISSUE TITLE
[FR] dual stereo sid support

### ISSUE THREAD

**Issue by randyrossi** [randyrossi/bmc64#46]
one sid = mono
two sids = stereo

**Comment by boras-pl** [comment]
If I may suggest a little improvement of existing dual sid support in Vice. Typically, DualSID works as two independent chips on separated port addresses. However, there are some h/w mods (which I personally tested on real hw) where two SIDs (especially 6581 & 8580) play in parallel the same data on the same port range. It produces some kind of pseudostereo sound for any tune programmed initially for only one SID.
http://blog.tynemouthsoftware.co.uk/2015/11/commodore-64-pseudo-stereo-dual-sid.html
https://www.youtube.com/watch?v=2Qlqeaxkp14

**Comment by boras-pl** [comment]
Another question. What about CPU usage of the second instance of SID? Is RPI3B+/4 fast enough to handle it?

**Comment by randyrossi** [comment]
I'm implementing dual sid now.  Pi3 and 4 are definitely fast enough to do dual sid but I plan on putting the call to generate the 2nd sid channel on it's own core so there should be no performance impact even for the Pi2.  Vice doesn't appear to support two sids on one base address but it could probably be done with some hacking.

**Comment by boras-pl** [comment]
I'll try to find my old patches for WinVice that exactly made that hacks. They are not the best in the world but may give some directions.

**Comment by randyrossi** [comment]
I think this would end up adding a bunch of resources to VICE code to control the engine/filters/model etc separately for each sid. I would have to plumb through the chip number through some APIs  It would also add more complexity to the UI to allow separate control of those settings which normally VICE would share among all SIDs.  Not sure if it's worth the divergence from VICE upstream.

**Comment by boras-pl** [comment]
This is a diff between very old Vice fetched from some SVN repo rev. 31474. I have no idea if it helps or not, but it surprisingly worked:

$ diff -cra vice-emu-code-31474-trunk vice-emu-code-31474-trunk_dualsid
diff -cra vice-emu-code-31474-trunk/vice/configure.proto vice-emu-code-31474-trunk_dualsid/vice/configure.proto
*** vice-emu-code-31474-trunk/vice/configure.proto	2016-07-25 23:56:09.000000000 +0200
--- vice-emu-code-31474-trunk_dualsid/vice/configure.proto	2016-07-31 00:13:12.000000000 +0200
***************
*** 180,190 ****
  is_beos_x11=no
  is_amiga=no
  
! HAVE_FULLSCREEN_SUPPORT="no "
! HAVE_OPENGL_SYNC_SUPPORT="no "
  HAVE_CAIRO_SUPPORT="no "
  HAVE_PANGO_SUPPORT="no "
! HAVE_HWSCALE_SUPPORT="no "
  USE_XF86_EXTENSIONS_SUPPORT="no "
  USE_MITSHM_SUPPORT="no "
  USE_XF86_VIDMODE_EXT_SUPPORT="no "
--- 180,190 ----
  is_beos_x11=no
  is_amiga=no
  
! HAVE_FULLSCREEN_SUPPORT="yes "
! HAVE_OPENGL_SYNC_SUPPORT="yes "
  HAVE_CAIRO_SUPPORT="no "
  HAVE_PANGO_SUPPORT="no "
! HAVE_HWSCALE_SUPPORT="yes "
  USE_XF86_EXTENSIONS_SUPPORT="no "
  USE_MITSHM_SUPPORT="no "
  USE_XF86_VIDMODE_EXT_SUPPORT="no "
diff -cra vice-emu-code-31474-trunk/vice/src/arch/unix/gui/uisid.h vice-emu-code-31474-trunk_dualsid/vice/src/arch/unix/gui/uisid.h
*** vice-emu-code-31474-trunk/vice/src/arch/unix/gui/uisid.h	2016-05-31 18:40:06.000000000 +0200
--- vice-emu-code-31474-trunk_dualsid/vice/src/arch/unix/gui/uisid.h	2016-07-27 22:16:33.000000000 +0200
***************
*** 31,36 ****
--- 31,37 ----
  
  #define SID_D4XX_MENU(menu, callback)                                                          \
  static ui_menu_entry_t menu[] = {                                                              \
+     { "$D400", UI_MENU_TYPE_TICK, (ui_callback_t)callback, (ui_callback_data_t)0xd400, NULL }, \
      { "$D420", UI_MENU_TYPE_TICK, (ui_callback_t)callback, (ui_callback_data_t)0xd420, NULL }, \
      { "$D440", UI_MENU_TYPE_TICK, (ui_callback_t)callback, (ui_callback_data_t)0xd440, NULL }, \
      { "$D460", UI_MENU_TYPE_TICK, (ui_callback_t)callback, (ui_callback_data_t)0xd460, NULL }, \
diff -cra vice-emu-code-31474-trunk/vice/src/arch/unix/gui/vsidui.c vice-emu-code-31474-trunk_dualsid/vice/src/arch/unix/gui/vsidui.c
*** vice-emu-code-31474-trunk/vice/src/arch/unix/gui/vsidui.c	2016-05-31 18:40:06.000000000 +0200
--- vice-emu-code-31474-trunk_dualsid/vice/src/arch/unix/gui/vsidui.c	2016-07-27 22:17:12.000000000 +0200
***************
*** 68,73 ****
--- 68,74 ----
  UI_MENU_DEFINE_RADIO(SidTripleAddressStart)
  
  static ui_menu_entry_t set_sid_stereo_address_d4xx_submenu[] = {
+     { "$D400", UI_MENU_TYPE_TICK, (ui_callback_t)radio_SidStereoAddressStart, (ui_callback_data_t)0xd400, NULL },
      { "$D420", UI_MENU_TYPE_TICK, (ui_callback_t)radio_SidStereoAddressStart, (ui_callback_data_t)0xd420, NULL },
      { "$D440", UI_MENU_TYPE_TICK, (ui_callback_t)radio_SidStereoAddressStart, (ui_callback_data_t)0xd440, NULL },
      { "$D460", UI_MENU_TYPE_TICK, (ui_callback_t)radio_SidStereoAddressStart, (ui_callback_data_t)0xd460, NULL },
diff -cra vice-emu-code-31474-trunk/vice/src/sid/resid.cc vice-emu-code-31474-trunk_dualsid/vice/src/sid/resid.cc
*** vice-emu-code-31474-trunk/vice/src/sid/resid.cc	2015-11-19 09:49:38.000000000 +0100
--- vice-emu-code-31474-trunk_dualsid/vice/src/sid/resid.cc	2016-07-27 23:01:18.000000000 +0200
***************
*** 79,84 ****
--- 79,86 ----
  
  typedef struct sound_s sound_t;
  
+ static int kolejny = 0;
+ 
  /* manage temporary buffers. if the requested size is smaller or equal to the
   * size of the already allocated buffer, reuse it.  */
  static SWORD *buf = NULL;
***************
*** 148,153 ****
--- 150,163 ----
  
      psid->factor = factor;
  
+     if(kolejny == 0)
+       model = 0;
+     if(kolejny == 1)
+       model = 1;
+ 
+     printf("######## kolejny=%d model=%d\n", kolejny, model);
+     kolejny++;
+ 
      switch (model) {
        default:
        case 0:
diff -cra vice-emu-code-31474-trunk/vice/src/sid/sid.c vice-emu-code-31474-trunk_dualsid/vice/src/sid/sid.c
*** vice-emu-code-31474-trunk/vice/src/sid/sid.c	2016-06-14 23:10:41.000000000 +0200
--- vice-emu-code-31474-trunk_dualsid/vice/src/sid/sid.c	2016-07-28 22:36:26.000000000 +0200
***************
*** 115,120 ****
--- 115,123 ----
      addr &= 0x1f;
  
      machine_handle_pending_alarms(0);
+     if((addr >= 0x19) && (addr <= 0x1c))
+         printf("############ sid_read_chip addr=%04X, chipno=%d\n",addr, chipno);
+ 
  
  #ifdef HAVE_MOUSE
      if (chipno == 0 && (addr == 0x19 || addr == 0x1a)) {
diff -cra vice-emu-code-31474-trunk/vice/src/sid/sid-resources.c vice-emu-code-31474-trunk_dualsid/vice/src/sid/sid-resources.c
*** vice-emu-code-31474-trunk/vice/src/sid/sid-resources.c	2016-06-14 23:10:41.000000000 +0200
--- vice-emu-code-31474-trunk_dualsid/vice/src/sid/sid-resources.c	2016-07-28 22:01:53.000000000 +0200
***************
*** 506,511 ****
--- 506,512 ----
          return -1;
      }
      resources_set_int("SidEngine", engine);
+     printf("###### Model %d\n");
      resources_set_int("SidModel", model);
  
      return 0;

**Comment by randyrossi** [comment]
I got this working.  I ended up adding my own Sid2Model resource and plumbing the chip number through to the sid implementations wasn't as cumbersome as I thought it was going to be.  I also got the 2nd SID stream produced by one of the idle cores so there's no performance penalty for adding a 2nd SID!  :)

**Comment by randyrossi** [comment]
Working in the 3.5 branch. Closing.
