### ISSUE TITLE
R1.7 thoughts

### ISSUE THREAD

**Issue by paolo2504** [randyrossi/bmc64#48]
Testing.. very good. 
 question with hotkeys: left ctrl should be imo the c= keyboard but it does nothing. Maybe i’m wrong: which is the c= key Please ?

Aldo: i’ve seen that bmc128 still default drive set to “none”

**Comment by lroby74** [comment]
you can choose a drive and save configuration

**Comment by randyrossi** [comment]
Control = Commodore key.  So they are one and the same.  

I haven't investigated any issues with C128.  You should be able to select 1541II though even if it doesn't select it by default.

**Comment by paolo2504** [comment]
Ok. Thanks.
