### ISSUE TITLE
USB Audio

### ISSUE THREAD

**Issue by neosquid** [randyrossi/bmc64#52]
Hi, is there a way to select USB Audio with BMC64? This would be great, if possible.

The 3.5mm PI audio out jack produces audio with crackling , so like many have USB audio to solve this problem.

**Comment by lroby74** [comment]
I am using composite audio video output from 3.5mm jack (going on CRT monitor) and audio is perfect, are you using HDMI for video output and 3.5mm jack  for audio?

**Comment by neosquid** [comment]
Yes, the 3.5mm audio is perfect, problem is that I have my pi hooked up behind my crt, it’s virtually inaccessible to change audio leads regularly (I’m also using Rasplex and Lakka on USB connection.) USB audio would make life more convenient.

**Comment by randyrossi** [comment]
This would require a driver which I don't plan on implementing.
