### ISSUE TITLE
[FR] BMSCPU64 (Super Cpu 64 version)

### ISSUE THREAD

**Issue by lroby74** [randyrossi/bmc64#53]
Would be nice to have Bare Metal SCPU64 version, this is not activable via VICE.INI, is another kernel required (like C128) :)

This may be better than BMC128 for have many accelerated games

**Comment by zzarko** [comment]
I also wanted to ask about scpu version. I have tried VICE on Raspbian on RPi 3B+, but it could only achieve about 25-30% of the real speed. The reason I still wanted to ask is RPi4, it should be considerably faster, maybe even fast enough.

**Comment by randyrossi** [comment]
I tried SCPU.  Rpi doesn't have enough horse power to pull it off.  Closing this.
