### ISSUE TITLE
[FR] Additional keys for file browsing and menu navigation

### ISSUE THREAD

**Issue by Jumpman64** [randyrossi/bmc64#57]
It would be comfy to use PgUp/PgDn (or Cursor left/right) keys for faster file browsing and 0-9 A-Z to jump directly to a letter.

Cursor right/left could be used to enter/leave a directory or the contents of a D64 file if that's a planned future feature. Maybe that's not so easy to realize so it can wait. :)
-RetroLynx from the Forum

**Comment by lroby74** [comment]
Function inserted with 1.9 version, this FR can be closed
