### ISSUE TITLE
[FR] Parallel cable support for SpeedDOS & DolphinDOS

### ISSUE THREAD

**Issue by Jumpman64** [randyrossi/bmc64#59]
For people who don't own JiffyDOS the parallel cable suppport (available in VICE) would be nice to have, so you can use SpeedDOS or other ROM files.
For DolphinDOS the Drive RAM Expansion would be needed as well.

**Comment by Jumpman64** [comment]
As randyrossi said adding parameters to the **vice.ini** should work.
I added this line to the vice.ini on the SD card to activate the parallel cable for device 8:
_Drive8ParallelCable=1_

putting the SpeedDOS ROMs (named "KERNAL" and "d1541II") into the "C64" folder as usual.
Tested with BMC64 1.9

For DolphinDOS3 these lines should work:
_Drive8RAM6000=1
Drive8ParallelCable=2_
(not tested)

@randyrossi 
If you are not planning to add menu entries for that you can close this [FR].
Thanks a lot for the hint and help!

**Comment by randyrossi** [comment]
Menu options were added in 3.1 so this can be done entirely from the menu now.
