### ISSUE TITLE
1541 (breadbin) and 1581 drive disappeared in Drive->ChangeModel with 1.9 version

### ISSUE THREAD

**Issue by corasaniti** [randyrossi/bmc64#60]
It seems that with the upgrade to the 1.9 version from the drive models (drive -> changeModel) the 1541 models (first version) and especially 1581 have disappeared, despite having in the c64/ folder  the respective roms files. Downgrading to 1.8 the two drive models reappear.
Thanks
Piero

**Comment by lroby74** [comment]
Confirm , same bug here

**Comment by randyrossi** [comment]
Try making sure bootstat.txt is in c64/ dir.  It moved and the default is incorrect. I will fix it in the next release.  In the meantime, moving bootstat.txt into that dir should fix it for you.

**Comment by corasaniti** [comment]
perfect moving the bootstat.txt file to c64/ drives reappear correctly.
I close the issue 
thanks
