### ISSUE TITLE
[question][progressive composite?] Is the composite output progressive or interlaced?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [randyrossi/bmc64#7]
Is the composite output progressive or interlaced?

By default RP with Linux provides interlaced composite output (PAL or NTSC).
Progressive output is possible with Raspbian by tweaking the configuration.

Is standard composite output with BMC64 progressive or interlaced?
If it is interlaced, is progressive output possible? How?

**Comment by randyrossi** [comment]
If the progressive output you can get from Raspbian is the result of editing config.txt, the same should work for this project.  There are different sdtv_mode options listed here : https://www.raspberrypi.org/documentation/configuration/config-txt/video.md

One of those options is progressive PAL (sdtv_mode 18).  So you can try that.  I'm not sure whether you have to change hdmi_mode to one of the 240p modes though.  It's worth experimenting and reporting back your findings.

**Comment by lroby74** [comment]
It's enough change SDTV_MODE to 18 for having progressive composite, it would be nice to have it on default on next releases
