### ISSUE TITLE
bmc64 with Expert Cartridge

### ISSUE THREAD

**Issue by billybicep** [randyrossi/bmc64#88]
Hi, is it possible to get the expert cartridge image to work with the bmc64? i have tried several different .crt images and they all just hang?

Thanks..

**Comment by randyrossi** [comment]
Try adding this to vice.ini in the [c64] section:

Expertfilename="/carts/c64/your_expert_cart.crt"
ExpertCartridgeEnabled=1
ExpertCartridgeMode=2

There's no menu option to attach that type of freezer.  I'd have to add it.

**Comment by randyrossi** [comment]
I don't think it works with VICE very well.  Other forum posts say it doesn't work with VICE unfortunately.  I can't get it to work with my desktop VICE build either.

**Comment by billybicep** [comment]
it works fine on WIN Vice, I've tried on 2.1 and 3.3, both work with my .crt file

**Comment by billybicep** [comment]
sorry, thats 3.1, not 3.3

**Comment by billybicep** [comment]
there's no vice.ini file, do i just create it?

**Comment by randyrossi** [comment]
If you save settings, it should appear.  Maybe I have the extension wrong?  Could be vice.rc but pretty sure it should show up as vice.ini.

**Comment by billybicep** [comment]
ok, I saved settings and it created the .ini file. i then added the expert settings above but it doesn't work. boots to black screen. if i press f12 and detach cartridge image c64 returns. i'm a real fan of the old expert cartridge, i always found it to be the best assembler for hacking and demo coding, is there likely to be a fix for this?

**Comment by randyrossi** [comment]
Can you point me to the file you're using?  I can try.

**Comment by billybicep** [comment]
[expert_cartridge.zip](https://github.com/randyrossi/bmc64/files/3989215/expert_cartridge.zip)

**Comment by billybicep** [comment]
this is the one I've used successfully on Win VICE.

**Comment by randyrossi** [comment]
Okay, that cartridge is actually not formatted correctly.  VICE probably doesn't care but it triggers an error in BMC64 file loader.  Try attaching this cartridge image:

[expert2.zip](https://github.com/randyrossi/bmc64/files/3989805/expert2.zip)

I'll fix the issue but in the meantime I think this will work.  I'm not sure if you still need those extra parameters.  You can try with/without.

**Comment by billybicep** [comment]
OK, that crt works if i attach it once booted up. if i save it as my default it doesn't boot but detaching and then re-attaching works. this is fine, its not a hassle to do it each time and at least the cart works which is the main thing. Thanks, much appreciated.

**Comment by billybicep** [comment]
having said that, it programs are crashing when the cart is loaded and the programs execute an IRQ. strange, i'll try it on Win VICE to see if its a general VICE issue.

**Comment by billybicep** [comment]
it doesnt work in Win VICE either, crashes the program and then corrupts the RAM.

**Comment by randyrossi** [comment]
Do the programs load and run without the cart installed?  I noticed that
cartridge has incorrect flags and has the wrong size which is probably
causing issues.  I can try to fix it.

**Comment by billybicep** [comment]
ok, just to confuse things further, it doesnt work on Win VICE 3.3 but it does work on Win VICE 2.1, so must be a VICE issue?

**Comment by billybicep** [comment]
The programs work fine without the cart

**Comment by randyrossi** [comment]
I think this is a VICE issue because I can't get it to work on recent versions of VICE.  Closing.
