### ISSUE TITLE
[FR] Support for 4 joysticks in parallel (UserportJoy, MAX_JOY_PORT limit)

### ISSUE THREAD

**Issue by hpingel** [randyrossi/bmc64#89]
Hi,

On an orginal C64, the Classicalgames / Protovision adapter allows to connect two additional joysticks to a PCB that is attached to the userport. Doing so, the C64 can handle 4 joysticks simultaneously. Vice normally is able to emulate this adapter: UserportJoy=1 and UserportJoyType=0.

With BMC64, the number of joysticks seems to be limited to two (compare value of MAX_JOY_PORTS). I would be nice to be able to use four joysticks for games like Bombmania, Shotgun or Frogs where four players can play simultaneously.

I know that this can be very complex to configure depending on the interface the joystick is attached to. Joysticks could be attached via USB, via keyboard command emulation (dabones C64USBKey), Keyrah, the Raspberry's GPIO-pins reserved by BMC64 etc.

Cheers,
Henning

**Comment by randyrossi** [comment]
This will be available in the next release (3.3).
