### ISSUE TITLE
TAP loading no longers works in v1.06

### ISSUE THREAD

**Issue by TomDDG** [randyrossi/bmc64#9]
Tapes that loaded fine in v1.05 no longer load just get a blank screen and the tape controls just crash the emulator

**Comment by randyrossi** [comment]
I'm able to load a tape.  Can I find the tape image you are using to try myself?

**Comment by TomDDG** [comment]
The tap in question which worked in v1.05 is Rambo First Blood Part 2 from the TOSEC collection. Once I select the tap the screen goes blank and the datasette controls just lock up the emulator.

As per the other issue I'm going to try a fresh install and the other kernel to see if that makes any difference.

**Comment by randyrossi** [comment]
I think I have a fix for this lockup issue.  You are using a Rpi 3?

**Comment by TomDDG** [comment]
No I'm using a pi 2b

**Comment by TomDDG** [comment]
Ok I did a fresh install and Rambo is working again. I can still get the emulator to lock up by doing a rewind and then play. The new SID is great by the way :-)

**Comment by TomDDG** [comment]
Sorry one other thing to point out regarding tape loading. If you insert a tape which the emulator doesn't like maybe a corrupt file or bad image then you get no message and it won't load. If a previous tape was in the drive then it will load that instead. Having some kind of error message would be great.

An example of this is Transformers from the TOSEC collection. If I try and attach this on Vice (windows) it errors saying cannot attatch, so must be a bad image. Trying this on BMC gives no message so when I try and load not sure why it isn't working. I guess a lot of the tape images in TOSEC are not compatible with VICE, not sure why.

All the tapes I can load on VICE work fine on BMC.

**Comment by randyrossi** [comment]
1.0.8 will show an error on disk/image attachment fail.  Looks like the original issue is also not a problem anymore.  Closing this issue.
