### ISSUE TITLE
[FR] Scanlines - Crt emu 

### ISSUE THREAD

**Issue by jimizanei** [randyrossi/bmc64#91]
like vice, is possible to set (config. files--how?!)   or add a  new menu/options to simulate the scanlines fx (crt emu) for the LCD  hdmi  tv/monitors ?! more better and realistic c64 picture with them. THX
vice.ini...not work like winvice (crt lines...)

**Comment by randyrossi** [comment]
I don't support CRT scanlines at the moment but I will be looking into it soon.  Thx.

**Comment by jimizanei** [comment]
Thanks Randy...because at LCD monitors/lcd is really bad , without scanlines (crt) fx...

**Comment by claudiacrt** [comment]
without crt / scalines options on hdmi/lcd screens is really horrible! 
very bad you not update with this option.
not every one, use bmc64 on crt monitors , hope you take little time also for that in your beta....

**Comment by jimizanei** [comment]
I try long time today, and I can say on lcd (various types an sizes) scanlines and video options work fine ...really good "pasta" with scanlines...now is possible to have a c64/vic20 beautyfull pictures also on lcd/hdmi !!!   REALLY thanks Randy!!   I found any no specific problems or bugs
not even slowdowns or lags, cause these new changes!!!  =)
