### ISSUE TITLE
Add a menu for open prg files possible?

### ISSUE THREAD

**Issue by CypherXG** [randyrossi/bmc64#95]
Hello
My question is:
Is it possible to add add a menu to open .prg files also?
It's hard to mount every time the correct IEC directory.
The problem ist that vice support IEC Filesystem, but it doesn't support the "cd" command.
You can not change the directory or change dir into a .d64 image.
A normal SD2IEC has a support for all that functions.

**Comment by randyrossi** [comment]
I thought loading PRG files did work using Autostart menu option.  I will check tonight.

**Comment by CypherXG** [comment]
Oh sorry. My fault. Ok i found it... :-)
